"""Attention-based watermark keypoint detector.

Identifies surviving watermark Regions of Interest (ROIs) in severely
cropped or fragmented images.  This enables the decoder to focus on
patches where watermark signal is strongest, rather than wasting capacity
on destroyed regions.

Architecture:
  1. **Patch feature extractor** — lightweight CNN that processes the image
     in overlapping patches to produce per-patch feature vectors.
  2. **Spatial self-attention** — Transformer encoder layers that let each
     patch attend to all others, learning which patches carry watermark
     signal based on cross-patch correlations.
  3. **Keypoint head** — per-patch binary classification (watermarked vs.
     destroyed) + confidence score.
  4. **Spatial attention map** — soft mask (B, 1, H, W) that can be used
     to weight the decoder input, suppressing non-watermarked regions.

Training:
  The detector is trained with ground-truth ROI masks generated by the ASL:
  regions that survive the attack have label 1, cropped/destroyed regions
  have label 0.  BCE loss + Dice loss.
"""

from __future__ import annotations

import math

import torch
import torch.nn as nn
import torch.nn.functional as F


# ---------------------------------------------------------------------------
# Patch feature extractor
# ---------------------------------------------------------------------------

class _PatchFeatureExtractor(nn.Module):
    """Extract per-patch feature vectors via small CNN.

    Partitions the input image into a grid of ``patch_size × patch_size``
    patches and encodes each into a ``feat_dim``-dimensional vector.

    Parameters
    ----------
    in_channels : int
        Input image channels (default 3).
    patch_size : int
        Spatial size of each patch (default 16).
    feat_dim : int
        Output feature dimension per patch (default 256).
    """

    def __init__(
        self,
        in_channels: int = 3,
        patch_size: int = 16,
        feat_dim: int = 256,
    ) -> None:
        super().__init__()
        self.patch_size = patch_size
        self.feat_dim = feat_dim

        # Small conv stack that reduces patch_size → 1×1
        layers: list[nn.Module] = []
        ch = in_channels
        out_ch = 64
        size = patch_size
        while size > 1:
            stride = 2 if size >= 4 else size
            kernel = stride + 1 if stride > 1 else 1
            pad = (kernel - 1) // 2
            layers.extend([
                nn.Conv2d(ch, out_ch, kernel, stride=stride, padding=pad, bias=False),
                nn.BatchNorm2d(out_ch),
                nn.ReLU(inplace=True),
            ])
            ch = out_ch
            out_ch = min(out_ch * 2, feat_dim)
            size = max(1, size // stride)
        layers.append(nn.AdaptiveAvgPool2d(1))
        layers.append(nn.Flatten())
        layers.append(nn.Linear(ch, feat_dim))

        self.cnn = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> tuple[torch.Tensor, int, int]:
        """Extract patch features.

        Parameters
        ----------
        x : (B, C, H, W) input image

        Returns
        -------
        features : (B, num_patches, feat_dim)
        grid_h : int — number of patches along height
        grid_w : int — number of patches along width
        """
        B, C, H, W = x.shape
        ps = self.patch_size

        # Pad if necessary
        pad_h = (ps - H % ps) % ps
        pad_w = (ps - W % ps) % ps
        if pad_h > 0 or pad_w > 0:
            x = F.pad(x, (0, pad_w, 0, pad_h), mode="reflect")
        _, _, Hp, Wp = x.shape
        grid_h, grid_w = Hp // ps, Wp // ps

        # Unfold into patches: (B, C, grid_h, ps, grid_w, ps) → (B*N, C, ps, ps)
        patches = x.unfold(2, ps, ps).unfold(3, ps, ps)  # (B, C, gh, gw, ps, ps)
        patches = patches.contiguous().view(B * grid_h * grid_w, C, ps, ps)

        # Extract features
        feats = self.cnn(patches)  # (B*N, feat_dim)
        feats = feats.view(B, grid_h * grid_w, self.feat_dim)

        return feats, grid_h, grid_w


# ---------------------------------------------------------------------------
# Positional encoding for patch positions
# ---------------------------------------------------------------------------

class _LearnedPositionalEncoding(nn.Module):
    """Learnable 2D positional encoding for patch grid positions."""

    def __init__(self, max_patches: int = 256, feat_dim: int = 256) -> None:
        super().__init__()
        self.pos_embed = nn.Parameter(torch.randn(1, max_patches, feat_dim) * 0.02)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        N = x.shape[1]
        return x + self.pos_embed[:, :N, :]


# ---------------------------------------------------------------------------
# Keypoint classification head
# ---------------------------------------------------------------------------

class _KeypointHead(nn.Module):
    """Per-patch binary classification: watermarked (1) or destroyed (0).

    Also outputs a confidence score.
    """

    def __init__(self, feat_dim: int = 256) -> None:
        super().__init__()
        self.mlp = nn.Sequential(
            nn.Linear(feat_dim, feat_dim // 2),
            nn.ReLU(inplace=True),
            nn.Dropout(0.1),
            nn.Linear(feat_dim // 2, 1),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Return logits (B, N, 1)."""
        return self.mlp(x)


# ---------------------------------------------------------------------------
# Loss: BCE + Dice
# ---------------------------------------------------------------------------

class KeypointDetectorLoss(nn.Module):
    """Combined BCE + Dice loss for keypoint detection.

    Parameters
    ----------
    dice_weight : float
        Weight for Dice loss vs BCE (default 1.0).
    """

    def __init__(self, dice_weight: float = 1.0) -> None:
        super().__init__()
        self.dice_weight = dice_weight

    def _dice_loss(self, pred: torch.Tensor, target: torch.Tensor) -> torch.Tensor:
        """Soft Dice loss."""
        pred_sig = pred.sigmoid()
        intersection = (pred_sig * target).sum()
        union = pred_sig.sum() + target.sum()
        return 1.0 - (2.0 * intersection + 1e-6) / (union + 1e-6)

    def forward(
        self, logits: torch.Tensor, target: torch.Tensor
    ) -> dict[str, torch.Tensor]:
        """Compute loss.

        Parameters
        ----------
        logits : (B, N, 1) — raw logits
        target : (B, N, 1) — binary labels {0, 1}

        Returns
        -------
        dict with ``loss``, ``bce``, ``dice``, ``accuracy``.
        """
        bce = F.binary_cross_entropy_with_logits(logits, target.float())
        dice = self._dice_loss(logits, target.float())
        loss = bce + self.dice_weight * dice

        with torch.no_grad():
            preds = (logits > 0).float()
            accuracy = (preds == target.float()).float().mean()

        return {
            "loss": loss,
            "bce": bce.detach(),
            "dice": dice.detach(),
            "accuracy": accuracy,
        }


# ---------------------------------------------------------------------------
# Main: WatermarkKeypointDetector
# ---------------------------------------------------------------------------

class WatermarkKeypointDetector(nn.Module):
    """Attention-based watermark keypoint detector.

    Identifies which spatial patches in a (possibly cropped) image still
    contain intact watermark signal.  Outputs a soft attention map that
    can be multiplied with the image before feeding to the decoder.

    Parameters
    ----------
    patch_size : int
        Spatial size of detection patches (default 16).
    feat_dim : int
        Feature dimension for patch embeddings (default 256).
    num_heads : int
        Attention heads in Transformer encoder (default 4).
    num_layers : int
        Number of Transformer encoder layers (default 4).
    max_patches : int
        Maximum number of patches for positional encoding (default 256).
    """

    def __init__(
        self,
        patch_size: int = 16,
        feat_dim: int = 256,
        num_heads: int = 4,
        num_layers: int = 4,
        max_patches: int = 256,
    ) -> None:
        super().__init__()
        self.patch_size = patch_size
        self.feat_dim = feat_dim

        self.patch_extractor = _PatchFeatureExtractor(
            in_channels=3, patch_size=patch_size, feat_dim=feat_dim
        )
        self.pos_encoding = _LearnedPositionalEncoding(max_patches, feat_dim)

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=feat_dim,
            nhead=num_heads,
            dim_feedforward=feat_dim * 4,
            dropout=0.1,
            activation="gelu",
            batch_first=True,
            norm_first=True,
        )
        self.transformer = nn.TransformerEncoder(
            encoder_layer, num_layers=num_layers
        )

        self.keypoint_head = _KeypointHead(feat_dim)

    def forward(
        self, x: torch.Tensor
    ) -> dict[str, torch.Tensor]:
        """Detect watermark keypoints.

        Parameters
        ----------
        x : (B, 3, H, W) — input image

        Returns
        -------
        dict with:
          - ``logits``: (B, N, 1) — per-patch watermark presence logits
          - ``attention_map``: (B, 1, H, W) — soft spatial attention mask
          - ``grid_h``, ``grid_w``: patch grid dimensions
        """
        B, _, H, W = x.shape
        ps = self.patch_size

        # Extract patch features
        feats, grid_h, grid_w = self.patch_extractor(x)  # (B, N, D)

        # Add positional encoding
        feats = self.pos_encoding(feats)

        # Self-attention across patches
        feats = self.transformer(feats)  # (B, N, D)

        # Classify each patch
        logits = self.keypoint_head(feats)  # (B, N, 1)

        # Build spatial attention map by reshaping logits to grid
        attn_grid = logits.sigmoid().view(B, 1, grid_h, grid_w)  # (B, 1, gh, gw)

        # Compute target output size (handle padding)
        pad_h = (ps - H % ps) % ps
        pad_w = (ps - W % ps) % ps
        out_h = H + pad_h
        out_w = W + pad_w

        # Upsample to original image resolution
        attn_map = F.interpolate(
            attn_grid, size=(out_h, out_w), mode="bilinear", align_corners=False
        )
        # Crop to original size
        attn_map = attn_map[:, :, :H, :W]

        return {
            "logits": logits,
            "attention_map": attn_map,
            "grid_h": grid_h,
            "grid_w": grid_w,
        }

    def get_weighted_image(
        self, x: torch.Tensor, threshold: float = 0.5
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """Apply detected attention map to weight image before decoding.

        Parameters
        ----------
        x : (B, 3, H, W) — input image
        threshold : float — hard threshold for the attention map (default 0.5)

        Returns
        -------
        weighted_image : (B, 3, H, W) — image with non-watermarked
            regions suppressed
        attention_map : (B, 1, H, W) — soft attention map
        """
        result = self.forward(x)
        attn = result["attention_map"]

        # Soft masking with floor to avoid complete zeroing
        weighted = x * (attn * 0.9 + 0.1)  # minimum 10% signal kept
        return weighted, attn
